In [2]:
import numpy as np

a=np.array([1,3,4,])

print (type(a))


# this is vectore array

<class 'numpy.ndarray'>


In [ ]:
#2D array
# this is metrics
b=np.array([[1,2,3],[1,2,4]])
print (b)

[[1 2 3]
 [1 2 4]]


In [ ]:
#3d array
# this is tenser
c=np.array([[1,2,3],[1,2,3],[1,2,3]])

print (c)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
#dtype

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
#np.arange

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
## with reshapte

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
#np.ones and np.zeros

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
#np.random

np.random.random((2,3))

array([[0.48700907, 0.16072307, 0.30519694],
       [0.4240233 , 0.7723099 , 0.28372325]])

In [23]:
#np.linspace=linear space

np.linspace(-10,20,5)



array([-10. ,  -2.5,   5. ,  12.5,  20. ])

In [24]:
#np.indentity

np.identity(2)

array([[1., 0.],
       [0., 1.]])

Array Attributes

In [28]:
a=np.arange(10)
b=np.arange(10).reshape(2,5)
c=np.arange(8).reshape(2,2,2)

a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#ndim = number of dimension
# is this find the what type of the array like what type of the dimension 

b.ndim

2

In [33]:
#shape == is this tell me in the dimension how mnay rows or collumn

b.shape
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
#size = in dimenshon is tell number of items in dimension

c.size

8

In [37]:
#itemsize = is this tell in per item how ocupy size in memory

a.itemsize

8

In [38]:
#dtype is this tell me what is the datatype is this use for the array

print (a.dtype)
print (b.dtype)
print (c.dtype)

int64
int64
int64


In [44]:
#astype is this basically use for the change the any array datatype as per the our requirments 


a.astype(np.int32)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Array Operation

In [4]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
#scaler operation

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [58]:
## relational operaion

a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [6]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[48., 76., 51.],
       [95.,  1., 66.],
       [76., 86.,  6.]])

In [10]:
np.prod(a1)

np.float64(45746285967360.0)

In [11]:
np.max(a1,axis=1)

array([76., 95., 86.])

In [12]:
##mean median 

np.mean(a1,axis=0)

array([73.        , 54.33333333, 41.        ])

In [13]:
## trigrometric = and is this rearly use for the codeing and etc...


np.sin(a1)

array([[-0.76825466,  0.56610764,  0.67022918],
       [ 0.68326171,  0.84147098, -0.02655115],
       [ 0.56610764, -0.92345845, -0.2794155 ]])

In [17]:
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
a2


np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [21]:
np.exp(a1)

array([[7.01673591e+20, 1.01480039e+33, 1.40934908e+22],
       [1.81123908e+41, 2.71828183e+00, 4.60718663e+28],
       [1.01480039e+33, 2.23524660e+37, 4.03428793e+02]])

In [26]:
np.ceil(np.random.random((2,3))*100)

array([[ 6., 92.,  3.],
       [59., 94., 94.]])

INDEXING & SLICING

In [5]:
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1[-2]

np.int64(8)

In [37]:
a2[1,3]

np.int64(7)

In [6]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [8]:
a3[1,0,1]

np.int64(5)

In [10]:
a3[0,0,1]

np.int64(1)

In [12]:
a3[1,1,0]

np.int64(6)

In [13]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a1[2:8:4]

array([2, 6])

In [16]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [48]:
a2[0:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [43]:
a2[1,0::3]

array([4, 7])

In [41]:
a2[0::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [21]:
a2[:,0]

array([0, 4, 8])

In [22]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [50]:
a3=np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [81]:
a3[::2,::4,::2]

array([[[ 0,  2]],

       [[18, 20]]])

In [68]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [65]:
a3[1,:,1]

array([10, 13, 16])

In [55]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

ITRETING

In [86]:
a1

for i in a1:
    print (i)

0
1
2
3
4
5
6
7
8
9


In [90]:
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [91]:
for i in a2:
    print (a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [88]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [92]:
for i in a3:
    print (a3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [93]:
for i in np.nditer(a3):
    print (i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [96]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [98]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

STACKING

In [104]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

a5

np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [114]:
h=np.vstack((a4,a5))

np.vsplit(h,2)
print (h)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [106]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [1]:
print ("hel")

hel


In [5]:
import numpy as np

np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [3]:
a

array([1, 3, 4])

In [5]:
a=12
b=24

In [6]:
print (a)
print (b)

12
24


In [ ]:
print (f"the number of a is {a} and number b is {b}")

the number of a is 12 and number b is 24


In [12]:
print (type(a))

<class 'int'>


In [5]:
a=(input("enter the name"))

if (a=="raj"):
    print (f"hello {a}")
else:
    print(f"you are not this person becuase you are {a} ")

you are not this person becuase you are nikhil 


In [12]:
b=int(input("enter the age"))

if b>60:
    print ("you are not elible for the driving")
elif b<18:
    print ("you are not eligible for the driving ")
elif b>=18:
    print("you are eligible for the driving")

you are not eligible for the driving 


In [ ]:
marks=int(input("enter the marks"))

if marks>100:
    print ("your grade is A+")
elif marks>95:
    print ("your grade is A")
elif marks>90:
    print ("your grade is B")
elif marks>80:
    print ("your grade is C")
elif marks>70:
    print ("your grade is D")
elif marks<50:
    print ("you are fail  ")


you are fail  


In [22]:
age=int(input("enter the age"))
id="CSA007"

if age>=18:
    useid=input("enter the id in capitle")
    if useid==id:
        print ("you are accessed")
    else:
        print ("your are id is incorrect")
else:
    print ("yor age is not greter than the 81")

your are id is incorrect


In [25]:
a=int(input("enter the number"))
if a<0:
    print ("your name is negetive")
elif a>0:
    print ("your number is positive")
elif a==0:
    print("yout number is zero")

your number is positive


In [30]:
c=int(input("enter the number"))

if c % 3==0:
    if c% 5==0:
        print ("fizbuzz")
elif(c/3):
    print ("this number is only divisible by 3")
elif(c/5):
    print ("this number is only divisible by 5")
else:
    print ("the number is not divisible 3 or 5")


this number is only divisible by 3


In [36]:
ml=int(input("enter the marks"))
dl=int(input("enter the marks"))
mld=int(input("enter the marks"))

averge=(ml+dl+mld)/3

if (ml<35 or dl<35 or mld<35):
    print ("your fail")

if averge>90:
    print (f"your grade is A and average is {averge}%")

elif averge>80:
    print (f"your grade is B and avergae is {averge}%")

elif averge>70:
    print (f"your grade is C and avergae{averge}%")

elif averge<=50:
    print (f"your grade is D and avrgae is {averge} ")

else:
    print ("you are fail")

you are fail


In [32]:
for i in range(14):
   if i % 2==0:
      print (i)

0
2
4
6
8
10
12


In [19]:
for i in range(1,6):
    print ("* "*i)

* 
* * 
* * * 
* * * * 
* * * * * 


In [45]:
for i in range(6,1):
    for j in range(1,i+1):
        print ("*",end="")
    print ()

In [ ]:
for i in range(1,6):
    for j in range(1,6):
        print ("* ",end="")
    print ()

jjjjj
jjjjj
jjjjj
jjjjj
jjjjj


In [ ]:
for i in range(1,6):
    for j in range(1,i+1):
        print (j,end="")
    print ()


1
12
123
1234
12345
123456
1234567
12345678
123456789
12345678910
1234567891011
123456789101112
12345678910111213
1234567891011121314


In [62]:
num=1

for i in range(1,6):
    for j in range(1,i+1):
        print (num,end=" ")
        num +=1

    print ()

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 
