In [ ]:
import numpy as np

a=np.array([1,3,4,])

print (type(a))


# this is vectore array

<class 'numpy.ndarray'>


In [ ]:
#2D array
# this is metrics
b=np.array([[1,2,3],[1,2,4]])
print (b)

[[1 2 3]
 [1 2 4]]


In [ ]:
#3d array
# this is tenser
c=np.array([[1,2,3],[1,2,3],[1,2,3]])

print (c)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [13]:
#dtype

np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [17]:
#np.arange

np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [18]:
## with reshapte

np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
#np.ones and np.zeros

np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [22]:
#np.random

np.random.random((2,3))

array([[0.48700907, 0.16072307, 0.30519694],
       [0.4240233 , 0.7723099 , 0.28372325]])

In [23]:
#np.linspace=linear space

np.linspace(-10,20,5)



array([-10. ,  -2.5,   5. ,  12.5,  20. ])

In [24]:
#np.indentity

np.identity(2)

array([[1., 0.],
       [0., 1.]])

Array Attributes

In [28]:
a=np.arange(10)
b=np.arange(10).reshape(2,5)
c=np.arange(8).reshape(2,2,2)

a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#ndim = number of dimension
# is this find the what type of the array like what type of the dimension 

b.ndim

2

In [33]:
#shape == is this tell me in the dimension how mnay rows or collumn

b.shape
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [34]:
#size = in dimenshon is tell number of items in dimension

c.size

8

In [37]:
#itemsize = is this tell in per item how ocupy size in memory

a.itemsize

8

In [38]:
#dtype is this tell me what is the datatype is this use for the array

print (a.dtype)
print (b.dtype)
print (c.dtype)

int64
int64
int64


In [44]:
#astype is this basically use for the change the any array datatype as per the our requirments 


a.astype(np.int32)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

Array Operation

In [46]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [48]:
#scaler operation

a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [58]:
## relational operaion

a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])