In [1]:
import numpy as np

NUMPY VS PYTHON LIST

In [4]:
a=[i for i in range(10000000)]
b=[i for i in range(10000000,20000000)]

c=[]

import time 

start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])

print(time.time()-start)

1.0615055561065674


In [6]:
import numpy as np

a=np.arange(10000000)
b=np.arange(10000000,20000000)

c=a+b

start=time.time()

print (time.time()-start)

0.0


In [8]:
#3 python exapmle for the memory

a=[i for i in range (10000000)]

import sys

sys.getsizeof(a)

89095160

In [10]:
a=np.arange(10000000,dtype=np.int32)
sys.getsizeof(a)

40000112

ADVANCE INDEXING

In [22]:
#Fensing Indexing

a=np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [19]:
a[[0,1,3]]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 9, 10, 11]])

In [23]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [25]:
a[:,[0,2,3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

BOOLEN INDEXING



In [37]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[91, 43, 91, 49],
       [38, 20, 35, 14],
       [67, 72, 54, 79],
       [ 3, 84, 22,  9],
       [42, 96, 77, 25],
       [36, 41, 83, 25]], dtype=int32)

In [ ]:
## find all number to greter than number


TypeError: '>' not supported between instances of 'list' and 'int'

In [40]:
b[b>50]

array([91, 91, 67, 72, 54, 79, 84, 96, 77, 83], dtype=int32)

In [48]:
# find the even number

b[b%2==0]

array([38, 20, 14, 72, 54, 84, 22, 42, 96, 36], dtype=int32)

In [51]:
b[(b>50) & (b%2==0)]

array([72, 54, 84, 96], dtype=int32)

In [ ]:
## find all number to divisiable into 7

b[(b%7==0)]

array([91, 91, 49, 35, 14, 84, 42, 77], dtype=int32)

In [56]:
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)

print (a)
print (b)

print (a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]
