In [1]:
import numpy as np

In [6]:
a=np.random.randint(1,100,15)
a

array([ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37],
      dtype=int32)

In [11]:
b=np.random.randint(1,100,24).reshape(6,4)
b

np.sort(b)

array([[11, 30, 52, 86],
       [41, 53, 69, 76],
       [ 3, 38, 40, 69],
       [18, 26, 31, 54],
       [ 8, 19, 64, 92],
       [27, 73, 80, 88]], dtype=int32)

## sorting 

In [13]:
np.sort(a)[::-1]

array([99, 91, 90, 87, 85, 76, 76, 55, 50, 50, 46, 45, 37, 30,  5],
      dtype=int32)

In [12]:
## 2d example

np.sort(b,axis=0)

array([[18, 26,  3,  8],
       [19, 40, 27, 11],
       [69, 41, 30, 38],
       [69, 52, 31, 53],
       [73, 80, 64, 54],
       [86, 92, 76, 88]], dtype=int32)

## apend

In [14]:
np.append(a,300)


array([  5,  55,  30,  85,  90,  50,  76,  99,  46,  87,  45,  50,  91,
        76,  37, 300])

In [17]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[8.60000000e+01, 5.20000000e+01, 3.00000000e+01, 1.10000000e+01,
        6.59138494e-01],
       [6.90000000e+01, 4.10000000e+01, 7.60000000e+01, 5.30000000e+01,
        2.30009491e-01],
       [6.90000000e+01, 4.00000000e+01, 3.00000000e+00, 3.80000000e+01,
        8.81831817e-02],
       [1.80000000e+01, 2.60000000e+01, 3.10000000e+01, 5.40000000e+01,
        3.61621561e-01],
       [1.90000000e+01, 9.20000000e+01, 6.40000000e+01, 8.00000000e+00,
        8.36478586e-01],
       [7.30000000e+01, 8.00000000e+01, 2.70000000e+01, 8.80000000e+01,
        2.88812335e-01]])

## concinate

In [19]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print (c)
print (d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [21]:
## concinate

np.concat((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## unique method 

In [24]:
e=np.array([1,2,3,3,4,4,4,4,5,6,6,7,88,8,])

e

array([ 1,  2,  3,  3,  4,  4,  4,  4,  5,  6,  6,  7, 88,  8])

In [25]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8, 88])

## expand

In [26]:
a

array([ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37],
      dtype=int32)

In [28]:
np.expand_dims(a,axis=0)

array([[ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37]],
      dtype=int32)

In [29]:
np.expand_dims(a,axis=1)

array([[ 5],
       [55],
       [30],
       [85],
       [90],
       [50],
       [76],
       [99],
       [46],
       [87],
       [45],
       [50],
       [91],
       [76],
       [37]], dtype=int32)

## where statement

In [30]:
a

array([ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37],
      dtype=int32)

In [32]:
np.where(a>60,"raj",a)

array(['5', '55', '30', 'raj', 'raj', '50', 'raj', 'raj', '46', 'raj',
       '45', '50', 'raj', 'raj', '37'], dtype='<U11')

In [33]:
np.where(a%2==0,0,a)

array([ 5, 55,  0, 85,  0,  0,  0, 99,  0, 87, 45,  0, 91,  0, 37],
      dtype=int32)

## argmax()

In [34]:
np.argmax(a)

np.int64(7)

In [35]:
b

array([[86, 52, 30, 11],
       [69, 41, 76, 53],
       [69, 40,  3, 38],
       [18, 26, 31, 54],
       [19, 92, 64,  8],
       [73, 80, 27, 88]], dtype=int32)

In [37]:
np.argmax(b,axis=0)

array([0, 4, 1, 5])

## cumsum

In [38]:
a

array([ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37],
      dtype=int32)

In [39]:
np.cumsum(a)

array([  5,  60,  90, 175, 265, 315, 391, 490, 536, 623, 668, 718, 809,
       885, 922])

In [40]:
b

array([[86, 52, 30, 11],
       [69, 41, 76, 53],
       [69, 40,  3, 38],
       [18, 26, 31, 54],
       [19, 92, 64,  8],
       [73, 80, 27, 88]], dtype=int32)

In [44]:
np.cumsum(b,axis=1)

array([[ 86, 138, 168, 179],
       [ 69, 110, 186, 239],
       [ 69, 109, 112, 150],
       [ 18,  44,  75, 129],
       [ 19, 111, 175, 183],
       [ 73, 153, 180, 268]])

## Percentile

In [45]:
a

array([ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37],
      dtype=int32)

In [46]:
np.percentile(a,80)

np.float64(87.60000000000001)

## Histogram

In [47]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90])


(array([1, 0, 0, 2, 2, 3, 0, 2, 3]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

## isin is seraching the array 

In [48]:
a

array([ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37],
      dtype=int32)

In [52]:
items=[10,20,30,40,50,60,70,80,90]

np.isin(items,a)

array([False, False,  True, False,  True, False, False, False,  True])

## Flip 


In [53]:
np.flip(a)

array([37, 76, 91, 50, 45, 87, 46, 99, 76, 50, 90, 85, 30, 55,  5],
      dtype=int32)

In [54]:
b

array([[86, 52, 30, 11],
       [69, 41, 76, 53],
       [69, 40,  3, 38],
       [18, 26, 31, 54],
       [19, 92, 64,  8],
       [73, 80, 27, 88]], dtype=int32)

In [55]:
np.flip(b)

array([[88, 27, 80, 73],
       [ 8, 64, 92, 19],
       [54, 31, 26, 18],
       [38,  3, 40, 69],
       [53, 76, 41, 69],
       [11, 30, 52, 86]], dtype=int32)

## Put

In [56]:
a

array([ 5, 55, 30, 85, 90, 50, 76, 99, 46, 87, 45, 50, 91, 76, 37],
      dtype=int32)

In [58]:
np.put(a,[0,1],[50,550])

a

array([ 50, 550,  30,  85,  90,  50,  76,  99,  46,  87,  45,  50,  91,
        76,  37], dtype=int32)

## Delete

In [59]:
a


array([ 50, 550,  30,  85,  90,  50,  76,  99,  46,  87,  45,  50,  91,
        76,  37], dtype=int32)

In [60]:
np.delete(a,[0,2,4])

array([550,  85,  50,  76,  99,  46,  87,  45,  50,  91,  76,  37],
      dtype=int32)

## Set fucniton 

In [62]:
m=np.array([1,2,3,4,5,6])
n=np.array([4,5,6,7,8,9,])

print (n)
print (m)

[4 5 6 7 8 9]
[1 2 3 4 5 6]


In [63]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.setdiff1d(m,n)

array([1, 2, 3])

In [66]:
np.intersect1d(m,n)

array([4, 5, 6])

## Clip

In [67]:
a

array([ 50, 550,  30,  85,  90,  50,  76,  99,  46,  87,  45,  50,  91,
        76,  37], dtype=int32)

In [68]:
np.clip(a,a_min=34,a_max=75)

array([50, 75, 34, 75, 75, 50, 75, 75, 46, 75, 45, 50, 75, 75, 37],
      dtype=int32)